modify OAuth IMAP
pluginsGLPI/doc pull request #80
Opened 2024-01-26 14:33 UTC by Otijom

2024-01-26 15:48 UTC, cconard96 requested changes

2024-01-26 15:48 UTC, cconard96 commented on source/oauthimap/index.rst
> +   Microsoft is gradually removing the TLS 1.0 and 1.1 protocols for all Microsoft 365 applications. In order to keep your collector running, you need to add an **Oauth IMAP** plugin available in the
```suggestion
   Microsoft is gradually removing the TLS 1.0 and 1.1 protocols for all Microsoft 365 applications. In order to keep your collector running, you need to add the **Oauth IMAP** plugin, which is available in the marketplace.
```

2024-01-26 15:48 UTC, cconard96 commented on source/oauthimap/index.rst
> +   This plugin is community and does not need a license. It is also available in Cloud.
```suggestion
   This plugin does not require a GLPI-Network subscription. It is also available in Cloud.
```

2024-01-26 15:48 UTC, cconard96 commented on source/oauthimap/index.rst
> +-  See you in the marketplace. Download Oauth IMAP and enable it
```suggestion
-  Go to the marketplace. Download Oauth IMAP and enable it
```

2024-01-26 15:48 UTC, cconard96 commented on source/oauthimap/index.rst
> +   **app registrations**
```suggestion
-  Open the `Azure Portal <https://portal.azure.com/#home>`__ for your tenant
-  In the search box type **registration** then select
   **App registrations**
```

2024-01-26 15:48 UTC, cconard96 commented on source/oauthimap/index.rst
> +-  Then click on **register**.
```suggestion
-  Click on **New registration**
-  Enter the desired name, select the type of account supported then enter the redirection URL (present in the configuration of the plugin from your GLPI interface:
   https://XXXXXXXXXXXXXX/marketplace/oauthimap/front/authorization.callback.php) specifying the **Web** option
-  Then click on **Register**.
```

2024-01-26 15:48 UTC, cconard96 commented on source/oauthimap/index.rst
> +-  Now in the **Oauth authorization** tab , we will **create an authorization**
```suggestion
-  Now in the **Oauth authorization** tab, click **Create an authorization**
```

2024-01-26 15:48 UTC, cconard96 commented on source/oauthimap/index.rst
> +-  When you click on :ti-add:**create authorization**, you will be redirected to the Microsoft services sign-in page
```suggestion
-  When you click on :ti-add:**Create authorization**, you will be redirected to the Microsoft services sign-in page
```

2024-01-26 16:17 UTC, cconard96 approved these changes

2024-01-29 07:54 UTC, cedric-anne reviewed
This plugin also works with Google/Gmail mailboxes. You should keep a small mention of it, even if you do not produce complete documentation of the configuration process like for Azure.

2024-01-29 07:54 UTC, cedric-anne commented on source/oauthimap/index.rst
> +   The Oauth tokens for the collector, retrieved during authentication with Azure by the OauthIMAP plugin, are “offline” tokens that delegate authorisation to a third-party application (GLPI). These
> (unless you change your password at a later date)

Are you sure of that? OAuth tokens should not be impacted by a password change.

2024-01-31 08:27 UTC, trasher commented on source/OauthSSOEntra/okta.rst
This one should probably not be added.

2024-01-31 09:49 UTC, Otijom commented on source/OauthSSOEntra/okta.rst
why do you think it shouldn't be added?

2024-01-31 15:09 UTC, merged