add plugin more satisfaction + transifex
pluginsGLPI/doc pull request #90
Opened 2024-01-29 14:40 UTC by Otijom

2024-01-29 15:35 UTC, cconard96 requested changes

2024-01-29 15:35 UTC, cconard96 commented on source/moresatisfaction/index.rst
> +- Select the type of question **yes/no** and enter the text that suits you
```suggestion
- Enter your survey and go to the **Question** tab
- Click on Add a question
- Select the type of question **Yes/No** and enter the text that suits you
```

2024-01-29 15:35 UTC, cconard96 commented on source/moresatisfaction/index.rst
> +- select the **text** type
```suggestion
- Select the **Text** type
```

2024-01-29 15:35 UTC, cconard96 commented on source/moresatisfaction/index.rst
> +- Click on Add when you are happy with your settings
```suggestion
- select the **Note** type
- You can select a score up to 10 and set a default value
- Click on "Add" when you are happy with your settings
```

2024-01-30 07:54 UTC, trasher requested changes

2024-01-30 07:54 UTC, trasher commented on source/moresatisfaction/index.rst
> +.. figure:: images/Satisfaction.png
Image seesm missing

2024-01-30 07:54 UTC, trasher commented on source/moresatisfaction/images/Satisfaction-2.png
Why "Entité racine" only is in french? All should be in english

2024-01-31 15:30 UTC, Otijom commented on source/moresatisfaction/index.rst
> +.. figure:: images/Satisfaction.png
It's ok for the picture

2024-01-31 15:30 UTC, Otijom commented on source/moresatisfaction/images/Satisfaction-2.png
no idea! it's been modified anyway

2024-02-01 06:42 UTC, merged